# Generated by Django 2.2.17 on 2021-01-09 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_cart_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
