# Generated by Django 2.2.17 on 2021-01-09 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordered_by',
        ),
    ]
