# Generated by Django 2.2.17 on 2021-01-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_order_ordered_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiveOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.PositiveIntegerField()),
                ('order_id', models.CharField(max_length=100)),
            ],
        ),
    ]
