export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
export const RESET_PASSWORD_CONFIRM_SUCCESS = 'RESET_PASSWORD_CONFIRM_SUCCESS';
export const RESET_PASSWORD_CONFIRM_FAIL = 'RESET_PASSWORD_CONFIRM_FAIL';
export const LOGOUT = 'LOGOUT';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';

// ---- self
export const PRODUCT_LOADED_SUCCESS = 'PRODUCT_LOADED_SUCCESS';
export const PRODUCT_LOADED_FAIL = 'PRODUCT_LOADED_FAIL';

//---product detail

export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';


//--add to cart


export const ADD_TO_CART = 'ADD_TO_CART';

export const DELETE_TO_CART = 'DELETE_TO_CART';
export const UPDATE_CART_QTY = 'UPDATE_CART_QTY';

export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';

export const ORDER_LOADED_SUCCESS = 'ORDER_LOADED_SUCCESS';
export const ORDER_LOADED_FAIL = 'ORDER_LOADED_FAIL';

export const ORDER_ITEM_LOADED_SUCCESS = 'ORDER_ITEM_LOADED_SUCCESS';
export const ORDER_ITEM_LOADED_FAIL = 'ORDER_ITEM_LOADED_FAIL';


export const ORDER_USER_ITEM_LOADED_SUCCESS = 'ORDER_USER_ITEM_LOADED_SUCCESS';
export const ORDER_USER_ITEM_LOADED_FAIL = 'ORDER_USER_ITEM_LOADED_FAIL';




export const RATING_SUCCESS = 'RATING_SUCCESS';
export const RATING_FAIL = 'RATING_FAIL';


export const EMPTY_TO_CART = 'EMPTY_TO_CART';

